language: java
before install: 
    - cd java
    
script:
   - ant -f BookMyShow/build.xml

jdk:
   - oraclejdk8
deploy:
  provider: releases
  api_key: "GITHUB OAUTH TOKEN"
  file: "FILE TO UPLOAD"
  skip_cleanup: true
  
